baseURL = 'https://ausoleil.netlify.app/'
languageCode = 'ja'
title = 'Au Soleil'
theme = 'papermod'

[params]
  [params.homeInfoParams]
  Title = "tellur blog"
  Content = "覚えたこととか"

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 12

[[menu.main]]
identifier = "profile"
name = "profile"
url = "/profile/"
weight = 15


[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

