baseURL = 'https://ausoleil.netlify.app/'
languageCode = 'ja'
title = 'Au Soleil'
theme = 'papermod'

# copyright = "Copyright © 2026 tellur"

[outputs]
    home = ["HTML", "RSS", "JSON"]

[params]
  math = true
 # [params.homeInfoParams]
 # Title = "tellur blog"
 # Content = "覚えたこととか"
 # customCSS = ["css/custom.css"]
  [params.profilemode]
  enabled = true # needs to be explicitly set
  Title = "tellur page"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/tellursn"
  # 検索
  [params.searchConfig]
        limit = 20
        threshold = 0.3
        strict = false

[taxonomies]
  tag = "tags"

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"
weight = 10

[[menu.main]]
identifier = "search"
name = "search"
url = "/search/"
weight = 12

[[menu.main]]
identifier = "profile"
name = "profile"
url = "/profile/"
weight = 15


[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
